//import moment from 'moment'; // Example for onSort prop
//import { NavLink } from 'react-router-dom';

export default [
    {
        "check":"",
        "notificationno": 1,
        "notificationheading": "New stock trading feature added",
        "notificationpreview": "Try out the latest trading features now!",
        "notificationtext":"We've added new stock trading features to our app. Log in and try them out now!",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/04/2023 3:00 PM",
        "view": 1,
        "delete": 1
    },
    {
        "check":"",
        "notificationno": 2,
        "notificationheading": "Upgrade to premium now and get 20% off!",
        "notificationpreview": "Limited time offer for premium users",
        "notificationtext":"Upgrade to our premium membership now and get 20% off for the first month! Enjoy exclusive trading features and benefits.",
        "notificationgroup": "Free users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/05/2023 10:00 AM",
        "view": 2,
        "delete": 2
    },
    {
        "check":"",
        "notificationno": 3,
        "notificationheading": "Important updates to our trading policies",
        "notificationpreview": "Please read our updated trading policies carefully",
        "notificationtext":"We've made important updates to our trading policies. Please log in and read them carefully to ensure compliance with our rules and regulations.",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/07/2023 11:00 AM",
        "view": 3,
        "delete": 3
    },
    {
        "check":"",
        "notificationno": 4,
        "notificationheading": "New user sign-up bonus",
        "notificationpreview": "Get a bonus when you sign up for our app",
        "notificationtext":"New users who sign up for our app now will receive a $10 bonus! Sign up and start trading today.",
        "notificationgroup": "New users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/08/2023 9:30 AM",
        "view": 4,
        "delete": 4
    },
    {
        "check":"",
        "notificationno": 5,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on May 10th from 2:00 AM to 4:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "05/10/2023 2:00 AM",
        "view": 5,
        "delete": 5
    },
    {
        "check":"",
        "notificationno": 6,
        "notificationheading": "New trading tips and strategies",
        "notificationpreview": "Improve your trading skills with our new tips and strategies",
        "notificationtext":"We've added new trading tips and strategies to our app. Log in and check them out now to improve your trading skills!",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/12/2023 10:00 AM",
        "view": 6,
        "delete": 6
    },
    {
        "check":"",
        "notificationno": 7,
        "notificationheading": "Upgrade to premium now and get exclusive benefits",
        "notificationpreview": "Unlock exclusive trading features and benefits with premium membership",
        "notificationtext":"Upgrade to our premium membership now and unlock exclusive trading features and benefits, including real-time market data, advanced analytics, and more!",
        "notificationgroup": "Free users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/15/2023 9:30 AM",
        "view": 7,
        "delete": 7
    },
    {
        "check":"",
        "notificationno": 8,
        "notificationheading": "New stock alerts feature added",
        "notificationpreview": "Get instant stock alerts sent to your phone",
        "notificationtext":"We've added a new stock alerts feature to our app. You can now set up alerts for price changes, news updates, and more. Download the latest version of our app to access this feature!",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/17/2023 3:30 PM",
        "view": 8,
        "delete": 8
    },
    {
        "check":"",
        "notificationno": 9,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on May 20th from 12:00 AM to 2:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "05/20/2023 12:00 AM",
        "view": 9,
        "delete": 9
    },
    {
        "check":"",
        "notificationno": 10,
        "notificationheading": "New stock research reports available",
        "notificationpreview": "Access our latest research reports now",
        "notificationtext":"We've added new stock research reports to our app. Log in and access them now to make more informed trading decisions!",
        "notificationgroup": "Premium users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/22/2023 10:00 AM",
        "view": 10,
        "delete": 10
    },
    {
        "check":"",
        "notificationno": 11,
        "notificationheading": "New user sign-up bonus",
        "notificationpreview": "Get a bonus when you sign up for our app",
        "notificationtext":"New users who sign up for our app now will receive a $20 bonus! Sign up and start trading today.",
        "notificationgroup": "New users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/25/2023 9:30 AM",
        "view": 11,
        "delete": 11
    },
    {
        "check":"",
        "notificationno": 12,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on May 28th from 1:00 AM to 3:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "05/28/2023 1:00 AM",
        "view": 12,
        "delete": 12
    },
    {
        "check":"",
        "notificationno": 13,
        "notificationheading": "Upgrade to premium now and get access to real-time market data",
        "notificationpreview": "Unlock real-time market data and more with premium membership",
        "notificationtext":"Upgrade to our premium membership now and unlock exclusive trading features and benefits, including real-time market data, advanced analytics, and more!",
        "notificationgroup": "Free users",
        "notificationscheduled": "No",
        "notificationdatetime": "05/30/2023 9:30 AM",
        "view": 13,
        "delete": 13
    },
    {
        "check":"",
        "notificationno": 14,
        "notificationheading": "Important updates to our trading policies",
        "notificationpreview": "Please read our updated trading policies carefully",
        "notificationtext":"We've made important updates to our trading policies. Please log in and read them carefully to ensure compliance with our rules and regulations.",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "06/02/2023 11:00 AM",
        "view": 14,
        "delete": 14
    },
    {
        "check":"",
        "notificationno": 15,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on June 5th from 2:00 AM to 4:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "06/05/2023 2:00 AM",
        "view": 15,
        "delete": 15
    },
    {
        "check":"",
        "notificationno": 16,
        "notificationheading": "New trading competition announced",
        "notificationpreview": "Compete with other traders for cash prizes",
        "notificationtext":"We've announced a new trading competition with cash prizes. Log in and join now to compete with other traders and win!",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "06/08/2023 10:00 AM",
        "view": 16,
        "delete": 16
    },
    {
        "check":"",
        "notificationno": 17,
        "notificationheading": "Upgrade to premium now and get 25% off!",
        "notificationpreview": "Limited time offer for premium users",
        "notificationtext":"Upgrade to our premium membership now and get 25% off for the first month! Enjoy exclusive trading features and benefits.",
        "notificationgroup": "Free users",
        "notificationscheduled": "No",
        "notificationdatetime": "06/12/2023 9:30 AM",
        "view": 17,
        "delete": 17
    },
    {
        "check":"",
        "notificationno": 18,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on June 15th from 12:00 AM to 2:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "06/15/2023 12:00 AM",
        "view": 18,
        "delete": 18
    },
    {
        "check":"",
        "notificationno": 19,
        "notificationheading": "New stock trading competition announced",
        "notificationpreview": "Join our latest trading competition now",
        "notificationtext":"We've announced a new stock trading competition with cash prizes. Log in and join now to compete with other traders and win!",
        "notificationgroup": "All users",
        "notificationscheduled": "No",
        "notificationdatetime": "06/18/2023 11:00 AM",
        "view": 19,
        "delete": 19
    },
    {
        "check":"",
        "notificationno": 20,
        "notificationheading": "Scheduled maintenance",
        "notificationpreview": "App will be temporarily unavailable during maintenance",
        "notificationtext":"We'll be performing scheduled maintenance on our app on June 20th from 1:00 AM to 3:00 AM EST. During this time, the app will be temporarily unavailable. We apologize for any inconvenience.",
        "notificationgroup": "All users",
        "notificationscheduled": "Yes",
        "notificationdatetime": "06/20/2023 1:00 AM",
        "view": 20,
        "delete": 20
    }
];
