//import moment from 'moment'; // Example for onSort prop
//import { NavLink } from 'react-router-dom';

export default [
    {
        txn_no: 1,
        txn_name: "John Smith",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "99",
        txn_script: "Basic",
        txn_datetime: "19/03/2023 05:00 PM",
        view: 1,
    },
    {
        txn_no: 2,
        txn_name: "Alice Johnson",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "100",
        txn_amount: "50.25",
        txn_script: "AAPL",
        txn_datetime: "21/03/2023 11:30 AM",
        view: 2,
    },
    {
        txn_no: 3,
        txn_name: "Bob Williams",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "49",
        txn_script: "Pro",
        txn_datetime: "22/03/2023 09:45 PM",
        view: 3,
    },
    {
        txn_no: 4,
        txn_name: "Carol Davis",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "50",
        txn_amount: "30.75",
        txn_script: "AMZN",
        txn_datetime: "23/03/2023 02:15 PM",
        view: 4,
    },
    {
        txn_no: 5,
        txn_name: "David Wilson",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "25",
        txn_amount: "17.50",
        txn_script: "GOOG",
        txn_datetime: "24/03/2023 10:00 AM",
        view: 5,
    },
    {
        txn_no: 6,
        txn_name: "Eva Martinez",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "79",
        txn_script: "Basic",
        txn_datetime: "25/03/2023 08:30 PM",
        view: 6,
    },
    {
        txn_no: 7,
        txn_name: "Frank Lee",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "75",
        txn_amount: "42.25",
        txn_script: "MSFT",
        txn_datetime: "26/03/2023 11:45 AM",
        view: 7,
    },
    {
        txn_no: 8,
        txn_name: "Grace Taylor",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "10",
        txn_amount: "8.50",
        txn_script: "FB",
        txn_datetime: "27/03/2023 03:00 PM",
        view: 8,
    },
    {
        txn_no: 9,
        txn_name: "Henry Clark",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "59",
        txn_script: "Pro",
        txn_datetime: "28/03/2023 07:15 PM",
        view: 9,
    },
    {
        txn_no: 10,
        txn_name: "Ivy Adams",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "20",
        txn_amount: "10.75",
        txn_script: "NFLX",
        txn_datetime: "29/03/2023 01:30 PM",
        view: 10,
    },
    {
        txn_no: 11,
        txn_name: "Jack Brown",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "25",
        txn_amount: "20.50",
        txn_script: "TSLA",
        txn_datetime: "30/03/2023 09:45 AM",
        view: 11,
    },
    {
        txn_no: 12,
        txn_name: "Karen Evans",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "69",
        txn_script: "Pro",
        txn_datetime: "31/03/2023 05:15 PM",
        view: 12,
    },
    {
        txn_no: 13,
        txn_name: "Larry Garcia",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "30",
        txn_amount: "18.25",
        txn_script: "AAPL",
        txn_datetime: "01/04/2023 11:30 AM",
        view: 13,
    },
    {
        txn_no: 14,
        txn_name: "Maggie Hernandez",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "50",
        txn_amount: "27.50",
        txn_script: "MSFT",
        txn_datetime: "02/04/2023 03:00 PM",
        view: 14,

    },
    {
        txn_no: 15,
        txn_name: "Nate Jackson",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "89",
        txn_script: "Basic",
        txn_datetime: "03/04/2023 08:30 PM",
        view: 15,
    },
    {
        txn_no: 16,
        txn_name: "Olivia Kim",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "40",
        txn_amount: "23.75",
        txn_script: "FB",
        txn_datetime: "04/04/2023 01:15 PM",
        view: 16,
    },
    {
        txn_no: 17,
        txn_name: "Peter Nguyen",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "15",
        txn_amount: "12.50",
        txn_script: "GOOG",
        txn_datetime: "05/04/2023 10:30 AM",
        view: 17,
    },
    {
        txn_no: 18,
        txn_name: "Queen Perez",
        txn_type: "P",
        txn_direction: "",
        txn_volume: "",
        txn_amount: "79",
        txn_script: "Pro",
        txn_datetime: "06/04/2023 06:45 PM",
        view: 18,
    },
    {
        txn_no: 19,
        txn_name: "Robert Lee",
        txn_type: "S",
        txn_direction: "Sell",
        txn_volume: "35",
        txn_amount: "21.50",
        txn_script: "AMZN",
        txn_datetime: "07/04/2023 02:00 PM",
        view: 19,
    },
    {
        txn_no: 20,
        txn_name: "Sarah Kim",
        txn_type: "S",
        txn_direction: "Buy",
        txn_volume: "5",
        txn_amount: "4.25",
        txn_script: "TSLA",
        txn_datetime: "08/04/2023 09:15 AM",
        view: 12,
    }
];
