name: React CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22  # The default SSH port
          script: |
            cd /home/hashmedia/tradefuel
            git pull
            npm install
            npm run build

      - name: Restart Node.js app with forever
        run: |
          # Navigate to your application directory
          cd /home/hashmedia/tradefuel

          # Replace 'your_app_name' with the name or ID of your specific 'forever' process
          forever restart server/index.js
